sudo: required
language: generic
compiler:
- gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - avishaya@amazon.com
    - avishayalon@gmail.com
env:
  global:
  - AFTER_INIT='env && echo `env` && df -h && echo `df -h`'
  - AFTER_RUN_TARGET_TEST='./install_deps.sh && rosenv ./run_integration_test.sh'
  - AWS_DEFAULT_REGION=us-west-2
  - WRITABLE_SOURCE=true
  - secure: rs5gyxnPkEdni7nG2P9fbzJ47pkknW9yNYVa9TXjIiEgzlkvK1Mujn8xVVfRQWyrrZp10IVaqhnDwWEaobc3v7Qnnzv6h0NomWZqZeWI4kXSLTsTKxSVo6sGbVubOQLoaWrwK6tPd00EgobBNDUo36MPdB3dObTxzCl/ikkkjxI1u/gw0BKIWk3VICW7QrYQPVjz/rUQxp65i+q5wiD7FNkIxWSSNmp1aV8FtEoo3NacFH80CSCjYNqSaGlayJ1mWYs2d4ABNjuPoStiillO/hpn7KYOWoKCrKEcak2TU0OiAEIzHbAh/J9UOCOTmiRMvlbwCaqEIv6WRWL0F6p3wfGSJ7iVR+5CyUgR6qri2V6b/ZEJLvbBt7jv3YzrCIfhiU5CtjaKITobk8u6XSanC+/jt25VDhXbvNpbwMOK6/ImnqCrf2VX64h0adCqFI3dL+/jbIH1Ob4j/BL4IwxIn9t7D1ade1P+JUHOas4IgvTBmaV9XWBhJp7r7ltjNpaOOUiUwynBD3txdu4676Kl2MXSwJ6Ja5q5a4XoDxO1iHVTowE2pqsqFNWT+bwXqyyCJn6Hi4BEh/duIQ9+2fbR+AzgV4eeteUpQ2l7JOYwppPCIbTvn1PckyWiTJ9DSG3+CHxLRccAEh9yRsmLK+Tdqsyi946mZpWTUKqszjSrtaY=
  - secure: LUw/2LLhTBTP+M6xlIVpcCNmO0zglUnuaQ0qu1ayRH3drMWKJrCsgKsnKyfB6vG4kewydLRvqJv3339OPsKaXL/ltnKEn2rD1pVCCHk3r7U8QoxjTRspWSdfJrA9YZN5IGTH18tGD0laXs2IS+J9or+4K6ojQeDQEDRrCsdQTY5w9C95mREGGwbw/JAI+pt1e511xX6M41OMqBxHqsEoLZoxfx9fXKd45E3iPAbc587c4xcWes/DNJpm5hoaIgFWfEEusbPu6Nai6NZmp4VFgDWm6QeZbmMRVgxRsaLrIQXYKa68pKgcZLlv9l/oyyPdjUkGwgWmhxm6IdBxgbVYlMZcAp+SWBZ8zrA4bwV6YW9mrIAVqQ7+KN+Y5LvcYA3q3tf6WpxOam28KBV/G6iRJ8yoHS4uBEzE6rj4rYDrLctpxn91cHEAfegJDaWsOPmfRkSyyzrNSRa/mEknakV8Qz1Gh7CG364KvyTq2gkBwy36nCDTxJX6IP7PQxGtJqVUMC7fItrwx+adV7UCqUhm7B6fCpQXCrdNFkFc9DNemxhzU2xSO/86x1GVNpK/SYzDP153lYmVh+5ACZhic+70Zm/enPhuEKW2jlg3dxdRlBRPse2VRQUxAi/XSwafIBovX+Dh1KDYkeaOBPF+YtWsEOU6rfu9ncpuGex9J3JxObk=
  matrix:
  - ROS_DISTRO="dashing" UPSTREAM_WORKSPACE=.rosinstall
install:
- touch travis
- echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" > .creds
- echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .creds
- echo "export AWS_DEFAULT_REGION=us-west-2" >> .creds
- git clone -b master https://github.com/ros-industrial/industrial_ci .ros_ci
script:
- ".ros_ci/travis.sh"
